// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiymwemqcmlkkofnahou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeW13ZW1xY21sa2tvZm5haG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjE4NzMsImV4cCI6MjA2NzYzNzg3M30.0Qv3O9mj_WLVGjzZxOPY3nmml6vGujH40lzYjso36eQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});